name: 同步Lms

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出上游仓库
        run: |
          git clone --mirror https://github.com/frappe/lms.git upstream-repo

      - name: 检出目标仓库
        run: |
          git clone https://atomgit.com/frappe/lms.git target-repo

      - name: 配置 Git 用户信息
        run: |
          cd target-repo
          git config user.name "wolone"  # 设置用户名
          git config user.email "71954466@qq.com"  # 设置邮箱

      - name: 推送所有分支和标签到目标仓库
        run: |
          cd upstream-repo
          git remote add target ../target-repo  # 添加目标仓库为远程
          git push --force --mirror target  # 强制推送所有分支和标签到目标仓库
