name: 同步Crm

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出上游仓库
        run: |
          git clone https://github.com/frappe/crm.git upstream-repo

      - name: 检出目标仓库
        run: |
          git clone https://atomgit.com/frappe/crm.git target-repo

      - name: 配置 Git 用户信息
        run: |
          cd target-repo
          git config user.name "wolone"  # 设置用户名
          git config user.email "71954466@qq.com"  # 设置邮箱

      - name: 推送 develop 分支到目标仓库
        run: |
          cd upstream-repo
          git checkout develop  # 切换到 develop 分支
          git push --force https://${{ secrets.TARGET_REPO_USERNAME }}:${{ secrets.TARGET_REPO_PASSWORD }}@atomgit.com/frappe/crm.git develop  # 强制推送到目标仓库

      - name: 推送 main 分支到目标仓库
        run: |
          cd upstream-repo
          git checkout main  # 切换到 main 分支
          git push --force https://${{ secrets.TARGET_REPO_USERNAME }}:${{ secrets.TARGET_REPO_PASSWORD }}@atomgit.com/frappe/crm.git main  # 强制推送到目标仓库
