name: 同步Lms

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出目标仓库
        run: |
          git clone https://atomgit.com/frappe/lms.git target-repo

      - name: 添加上游仓库
        run: |
          cd target-repo
          git remote add frappe https://github.com/frappe/lms.git
          git fetch frappe

      - name: 配置 Git 用户信息
        run: |
          cd target-repo
          git config user.name "wolone"  # 设置用户名
          git config user.email "71954466@qq.com"  # 设置邮箱

      - name: 同步所有分支
        run: |
          cd target-repo
          for branch in $(git branch -r | grep 'frappe/' | sed 's/origin\///'); do
            git checkout $branch || git checkout -b $branch  # 检出分支，如果不存在则创建
            git fetch frappe  # 获取上游更新
            git reset --hard frappe/$branch  # 强制重置目标的分支为上游的分支
            git push --force https://${{ secrets.TARGET_REPO_USERNAME }}:${{ secrets.TARGET_REPO_PASSWORD }}@atomgit.com/frappe/lms.git $branch  # 强制推送到目标仓库
          done
