name: 同步Crm

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检查目标仓库是否存在
        id: check_repo
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.TARGET_REPO_USERNAME }}:${{ secrets.TARGET_REPO_PASSWORD }}" https://atomgit.com/frappe/crm.git)
          echo "::set-output name=repo_exists::$RESPONSE"

      - name: 创建目标仓库
        if: steps.check_repo.outputs.repo_exists != '200'
        run: |
          curl -u "${{ secrets.TARGET_REPO_USERNAME }}:${{ secrets.TARGET_REPO_PASSWORD }}" -d '{"name": "crm"}' https://atomgit.com/api/v1/repos

      - name: 检出上游仓库
        run: |
          git clone --mirror https://github.com/frappe/crm.git upstream-repo

      - name: 检出目标仓库
        run: |
          git clone https://atomgit.com/frappe/crm.git target-repo

      - name: 配置 Git 用户信息
        run: |
          cd target-repo
          git config user.name "wolone"  # 设置用户名
          git config user.email "71954466@qq.com"  # 设置邮箱

      - name: 推送上游的所有分支到目标仓库
        run: |
          cd upstream-repo
          git remote add target ../target-repo  # 添加目标仓库为远程
          git push --force --all target  # 强制推送所有分支到目标仓库
